### PR TITLE
Avoid crash for non-elementary OS

### PR DESCRIPTION
**Pull request by paulcarroty**
https://github.com/Philip-Scott/Notes-up/issues/236

### CODE REVIEW

**Comment by decathorpe** [comment]
Which functionality is this flag disabling? If it's only about contractor (like you mentioned in issue #1), I can add contractor as a dependency for the Notes-up package, instead.

**Comment by paulcarroty** [comment]
Google know nothing about it.

**Comment by decathorpe** [comment]
I pushed an updated build to the COPR repo.

Can you check if it fixes the crash?

**Comment by paulcarroty** [comment]
Now it works, thx.

**Comment by decathorpe** [comment]
Great!

**Pull request closed without merging**
